// 全てのページに共通するレイアウト
import './globals.css'
import type { Metadata } from 'next'
import Header from './components/Header'
import Navbar from './components/Navbar'
import SearchBox from './components/SearchBox'
import Providers from "./Providers"; // next-themes の ThemeProvider を使って、システムのテーマを取得して、 dark モードに切り替える Provider


export const metadata: Metadata = {
  title: 'IMDB Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <Providers>
          {/* Header */}
          <Header />

          {/* Navbar */}
          <Navbar />

          {/* Search */}
          <SearchBox />

          {/* その他の全てのページ */}
          {children}
        </Providers>
      </body>
      </html>
  )
}
